# Generated by Django 6.0.6 on 2026-06-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projetu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulu', models.CharField(max_length=50)),
                ('deskrisaun', models.TextField()),
                ('imajem', models.ImageField(upload_to='')),
                ('teknolojia', models.CharField(max_length=100)),
                ('github_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
