# Generated by Django 6.0.6 on 2026-06-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naran', models.CharField(max_length=100)),
                ('data_moris', models.TimeField()),
                ('biografia', models.TextField()),
                ('hela_fatin', models.CharField(max_length=30)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv_uploads/')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfil/')),
            ],
            options={
                'verbose_name_plural': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='Sertifikadu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulu', models.CharField(max_length=50)),
                ('tinan', models.CharField(max_length=4)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
