# Generated by Django 6.0.6 on 2026-06-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfil_sertifikadu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='data_moris',
            field=models.DateField(),
        ),
    ]
